from __future__ import annotations

from asn1crypto.core import Integer, ObjectIdentifier, Sequence, SetOf

class CertificateSet(SetOf): ...
class CMSAttributes(SetOf): ...
class CMSVersion(Integer): ...
class ContentInfo(Sequence): ...
class ContentType(ObjectIdentifier): ...
class DigestAlgorithms(SetOf): ...
class RevocationInfoChoices(SetOf): ...
class SignerInfo(Sequence): ...
class SignerInfos(SetOf): ...
