from __future__ import annotations

def hexStr(data: bytes) -> str: ...

def num2binary(l: int, bits=32) -> str: ...

def strjoin(iterable, joiner: str = "") -> str: ...

def tobytes(
    s: str | bytes, encoding: str = "ascii", errors: str = "strict"
) -> bytes: ...
